### ISSUE TITLE
this don't work for me

### ISSUE THREAD

**Issue by carloscarcamo** [ikarius6/codeigniter-trusted-hosts#1]
Maybe i'm doing something wrong, how this supposed to work and how this is supposed to be used?

At the end of my application/config/config.php I added this line:

``` php
$config['trusted_hosts'] = array('localhost', 'mywebsite.com');
```

And copy the MY_config.php to application/core/

then I used this python script to test: https://github.com/1N3/XSSTracer

```
 $ ./xsstracer.py mywebsite.com 80
    __  ______ _____ 
    \ \/ / ___|_   _|
     \  /\___ \ | |  
     /  \ ___) || |  
    /_/\_|____/ |_|  

+ -- --=[Cross-Site Tracer v1.3 by 1N3 @ CrowdShield
+ -- --=[Target: mywebsite.com:80
+ -- --=[Site not vulnerable to Cross-Site Tracing!
+ -- --=[Site vulnerable to host header injection!
```

**Comment by ikarius6** [comment]
Sure man, the reason is the next:

My code works to avoid the use of untrusted HOST headers on your project, for example, an attacker send a request with HOST: devildomain.com, I don't stop the request, the request is processed normally by CI, but with a difference, if the HOST is untrusted I protect the base_url (than is used for all the site to make redirects or print links) replacing it by a localhost.

If you see [MY_Config.php](https://github.com/ikarius6/codeigniter-trusted-hosts/blob/master/application/core/MY_Config.php#L35-L42) you can see the proccess.

``` php
if ( $trusted ) {
    $base_url = (is_https() ? 'https' : 'http').'://'.$_SERVER['HTTP_HOST']
        .substr($_SERVER['SCRIPT_NAME'], 0, strpos($_SERVER['SCRIPT_NAME'], basename($_SERVER['SCRIPT_FILENAME'])));
}
else
{
    $base_url = 'http://localhost/';
}
```

I took a look at [XSSTracer](https://github.com/1N3/XSSTracer/blob/master/xsstracer.py#L96-L112), and I saw than it only sends a GET http request, then just parse the response to find the same HOST header, but actually don't check the use of HOST header on your application, so... your application is protected but maybe your webserver not much.

Actually, the code is to protect the variable $base_url, if you use the HOST header with raw php code you can still on danger, so, you have another choice... if you feel paranoid, you can even overwrite the HOST header for your CI app if the domain is untrusted,  you could add

$_SERVER['HTTP_HOST'] = "localhost";

I've did that for you in a new [commit](https://github.com/ikarius6/codeigniter-trusted-hosts/commit/7abe898e057457ac9aea5f07dbffb28587d3e047). With the new commit I got:

←[92m+ -- --=[Site not vulnerable to host header injection!←[0m

I hope this help a little, thanks for your comments.

**Comment by carloscarcamo** [comment]
Thanks!
Just a suggestion on your code, maybe you're using codeigniter 3, but if someone is using codeigniter 2.x maybe this the config code will show an error when using `is_https()`, I think you could use `$_SERVER['HTTPS']` instead, like this:

``` php
if ( $trusted ) {
    $base_url = (isset($_SERVER['HTTPS']) ? 'https' : 'http').'://'.$_SERVER['HTTP_HOST']
        .substr($_SERVER['SCRIPT_NAME'], 0, strpos($_SERVER['SCRIPT_NAME'], basename($_SERVER['SCRIPT_FILENAME'])));
}
```
